### ISSUE TITLE
Install django-image-sitemaps through pip is not working

### ISSUE THREAD

**Issue by IuryAlves** [akarzim/image-sitemaps#1]
The command:

`pip install -vvvv django-image-sitemaps`

Outputs:

```
Collecting django-image-sitemaps
  1 location(s) to search for versions of django-image-sitemaps:
  * https://pypi.python.org/simple/django-image-sitemaps/
  Getting page https://pypi.python.org/simple/django-image-sitemaps/
  Looking up "https://pypi.python.org/simple/django-image-sitemaps/" in the cache
  Current age based on date: 490
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 490
  Analyzing links from page https://pypi.python.org/simple/django-image-sitemaps/
    Skipping link https://pypi.python.org/packages/2c/61/4a708c6b64ce6ce25f6c3ddab3a187d97dc07ad97254c8c00614cec8f147/django_image_sitemaps-1.05-py2.7.egg#md5=5a769b32b1731126e2135e7c2f1a1de9 (from https://pypi.python.org/simple/django-image-sitemaps/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/38/3d/b1e408273d596dd3d87ad0d949c59dd5adc60469df3df411edaa5f91ad1a/django_image_sitemaps-1.02-py2.7.egg#md5=d506ed012849424a21627cf1189c2bfe (from https://pypi.python.org/simple/django-image-sitemaps/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/77/39/594b778df7bc0ca98845beecbe5a3154a39631bc6da8c96b8c857d94e339/django_image_sitemaps-1.03-py2.7.egg#md5=cc7e83345538aa03bebe1e656db7dbae (from https://pypi.python.org/simple/django-image-sitemaps/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/7e/39/5491d592319a4924c5d0816afe2a9d5caec9e96fbd5166ea6d26381e608b/django_image_sitemaps-1.04-py2.7.egg#md5=2cfb9fe02cf27cb9dec081cfd8f36c57 (from https://pypi.python.org/simple/django-image-sitemaps/); unsupported archive format: .egg
  Could not find a version that satisfies the requirement django-image-sitemaps (from versions: )
Cleaning up...
No matching distribution found for django-image-sitemaps
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 268, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python2.7/site-packages/pip/index.py", line 491, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for django-image-sitemaps
```

**Comment by akarzim** [comment]
Hello @IuryAlves,

I hadn't noticed your issue until today 😱
I just uploaded the 1.1.0 version of the package, freshly tagged, and it seems to work fine now.

**Comment by IuryAlves** [comment]
Thanks @akarzim  = )
